Repository The-GameDJs/CostumeCurse, pull requests merged in 2020-12, with the labels that each got.

#78 Update Shared Main Scene
  Assets/Scenes/Main_Scene.unity
Labels: p0

#80 Smooth Out Combat Transitions
  Assets/Scripts/CameraArea.cs
  Assets/Scripts/CameraRig.cs
  Assets/Scripts/Combat/Combantants/Combatant.cs
  Assets/Scripts/Combat/CombatSystem.cs
  Assets/Scripts/CombatZone.cs
Labels: bug

#88 Add Combat Movement Initiation
  Assets/Prefabs/Combat Zone.prefab
  Assets/Scenes/Main_Scene.unity
  Assets/Scripts/CombatZone.cs
Labels: p1
